services:
  db: 
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: marketplace_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: